name: VRP-Core
version: 0.1
authors: [wickedizerd, goldminer931]
main: VRPCore.VRPCore
api-version: 1.16
description: Velocity Role Playing Core Plugin
depend: [Vault]
softdepend: [LuckPerms]
commands:
  /es:
  cinematic:
  forecast: